# Generated by Django 5.1.6 on 2025-11-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome da certificação')),
                ('institution', models.CharField(max_length=150, verbose_name='Instituição')),
                ('issue_date', models.DateField(verbose_name='Data de emissão')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Data de expiração')),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da credencial')),
                ('credential_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL da credencial')),
                ('order_index', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Certificação',
                'verbose_name_plural': 'Certificações',
                'db_table': 'certification',
                'ordering': ['order_index', '-issue_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('subject', models.CharField(max_length=150, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebida em')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida?')),
            ],
            options={
                'verbose_name': 'Mensagem de contato',
                'verbose_name_plural': 'Mensagens de contato',
                'db_table': 'contact_message',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=150, verbose_name='Instituição')),
                ('degree', models.CharField(max_length=150, verbose_name='Curso / Grau')),
                ('field_of_study', models.CharField(blank=True, max_length=150, null=True, verbose_name='Área de estudo')),
                ('start_date', models.DateField(verbose_name='Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Conclusão')),
                ('is_current', models.BooleanField(default=False, verbose_name='Cursando atualmente?')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('order_index', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Formação',
                'verbose_name_plural': 'Formações',
                'db_table': 'education',
                'ordering': ['order_index', '-start_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150, verbose_name='Empresa')),
                ('role', models.CharField(max_length=150, verbose_name='Cargo')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização')),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de término')),
                ('is_current', models.BooleanField(default=False, verbose_name='Emprego atual?')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('order_index', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
                'db_table': 'experience',
                'ordering': ['order_index', '-start_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Idioma')),
                ('level', models.CharField(max_length=50, verbose_name='Nível')),
                ('order_index', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'db_table': 'language',
                'ordering': ['order_index', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('slug', models.SlugField(help_text='Usado na URL de detalhes do projeto.', max_length=150, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(verbose_name='Descrição curta')),
                ('long_description', models.TextField(blank=True, null=True, verbose_name='Descrição completa')),
                ('repo_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Repositório')),
                ('demo_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Demo / Deploy')),
                ('highlight', models.BooleanField(default=False, verbose_name='Destaque na home?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'db_table': 'project',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('hero', 'Hero'), ('skills', 'Skills'), ('experience', 'Experience'), ('certifications', 'Certifications'), ('education', 'Education'), ('services', 'Services'), ('projects', 'Projects'), ('languages', 'Languages'), ('contact', 'Contact')], max_length=32, unique=True, verbose_name='Seção')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('order_index', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Configuração de seção',
                'verbose_name_plural': 'Configurações de seções',
                'db_table': 'section_config',
                'ordering': ['order_index'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Título do serviço')),
                ('short_description', models.TextField(verbose_name='Descrição curta')),
                ('detailed_description', models.TextField(blank=True, null=True, verbose_name='Descrição detalhada')),
                ('icon_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ícone')),
                ('highlight', models.BooleanField(default=False, verbose_name='Destaque?')),
                ('order_index', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'service',
                'ordering': ['order_index', 'title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('devops', 'DevOps'), ('database', 'Banco de dados'), ('other', 'Outros')], default='other', max_length=50, verbose_name='Categoria')),
                ('level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nível')),
                ('icon_key', models.CharField(blank=True, help_text="Chave usada no front para resolver o ícone (ex.: 'python').", max_length=100, null=True, verbose_name='Ícone')),
                ('order_index', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'skill',
                'ordering': ['order_index', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('job_title', models.CharField(max_length=150, verbose_name='Cargo / Título profissional')),
                ('short_bio', models.TextField(verbose_name='Biografia curta')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('github_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='GitHub')),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='LinkedIn')),
                ('portfolio_slug', models.SlugField(help_text='Identificador único usado na URL pública do portfólio.', unique=True, verbose_name='Slug do portfólio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'db_table': 'app_user',
                'ordering': ['full_name'],
                'managed': False,
            },
        ),
    ]
