# Generated by Django 5.1.6 on 2025-12-31 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['order_index', '-issue_date'], 'verbose_name': 'Certificação', 'verbose_name_plural': 'Certificações'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mensagem de contato', 'verbose_name_plural': 'Mensagens de contato'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order_index', '-start_date'], 'verbose_name': 'Formação', 'verbose_name_plural': 'Formações'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order_index', '-start_date'], 'verbose_name': 'Experiência', 'verbose_name_plural': 'Experiências'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['order_index', 'name'], 'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AlterModelOptions(
            name='sectionconfig',
            options={'ordering': ['order_index'], 'verbose_name': 'Configuração de seção', 'verbose_name_plural': 'Configurações de seções'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order_index', 'title'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order_index', 'name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['full_name'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
    ]
